### ISSUE TITLE
basti cleanup not respecting region flag

### ISSUE THREAD

**Issue by andreas-mueller-bb** [basti-app/basti#104]
## Bug Description

When having multiple setups of basti in different regions such as eu-central-1 and us-west-2 basti cleanup doesn't respect the --aws-region flag when it comes to IAM resources.

## Steps to Reproduce

1. Run `basti init --aws-region eu-central-1`
2. Run `basti init --aws-region us-west-2`
3. Verify basti is working in both regions & that an IAM role / instance profile exists for each region
4. Run `basti cleanup --aws-region us-west-2`

## Expected Behavior

After the command in step 4 all basti resources wich were deployed in step 2 should have been removed and all basti resources which were deployed in step 1 should stil be existing.

## Current Behavior

Unfortunately basti cleans _ALL_ IAM resources including the role / instance profile that belongs to the eu-central-1 setup wich essentially renders that setup unusable as a connection to the instance via Session Manger is no longer possible.

## Possible Solution (Optional)

Somehow make basti aware of the region of the setup which IAM resource belongs to so that basti cleanup does not remove resources which it shouldn't remove.

Apart from that thanks for proving such an elegant solution! :)

**Comment by BohdanPetryshyn** [comment]
Hey @andreas-mueller-bb, thanks for reporting this! I'll take a look soon! Meanwhile, would you consider contributing to Basti?

**Comment by andreas-mueller-bb** [comment]
Hi @BohdanPetryshyn 
I would. But unfortunately I lack the necessary programming skills to do so 😅

**Comment by BohdanPetryshyn** [comment]
The issue was resolved in [basti@1.6.3](https://github.com/basti-app/basti/releases/tag/basti%401.6.3) 🚀
