### ISSUE TITLE
Default Encryption for ec2 instances volumes

### ISSUE THREAD

**Issue by GustavoAdrianGimenez** [basti-app/basti#94]
## Feature Description

To enhance security, it's important to attach encrypted EBS volumes for EC2 instances.

## Use Case

NA

## Proposed Solution
Perhaps we could enable the encryption configuration [here](https://github.com/basti-app/basti/blob/main/packages/basti/src/aws/ec2/create-ec2-instance.ts#L40) . We would be pleased to collaborate if you are in agreement

## Related Issues/PRs

NA

**Comment by BohdanPetryshyn** [comment]
Hi @GustavoAdrianGimenez, thank you for reporting this!

I can confirm that the created EBS volume is not encrypted and can be encrypted with the [RunInstancesCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ec2/command/RunInstancesCommand/).

You're very welcome to contribute to Basti by implementing this enhancement ❤️

**Comment by BohdanPetryshyn** [comment]
The changes have to be mirrored in Basti CDK [here](https://github.com/basti-app/basti/blob/eae6cdf29ff8329ed166a10d1a9d073ad7b1ccf8/packages/basti-cdk/src/basti-instance.ts#L155).
